<?

function replaceSr($str){}
function replaceSl($str){}

// играет системный звук
function message_beep($flag){}

// возвращает псевдо-случайно целое число от 0 до X
function random($x){}

// копирует текст в буфер обмена
function clipboard_setText($text){}

// возвращает текст из буфера обмена
function clipboard_getText(){}

// копирует массив файлов в буфер
function clipboard_setFiles($files){}

// возвращает массив файлов из буфера
function clipboard_getFiles(){}

// копирует картинку из текста или компонента в буфер обмена
function clipboard_assign($picture, $format = null){}